// -------------------------------------------------------------
//
// Module: fir_filter_mat
// Generated by MATLAB(R) 9.10 and Filter Design HDL Coder 3.1.9.
// Generated on: 2021-07-15 15:22:09
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: C:\Users\Administrator\Desktop
// Name: fir_filter_mat
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module overdrive
               (
                clk,
                clk_enable,
                reset,
                overdrive_in,
                overdrive_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [15:0] overdrive_in; 
  output  signed [15:0] overdrive_out; 

//parameter define


//reg define
reg signed threshold=16'b0100000000000000;
reg  [15:0] overdrive;
//wire define

 
//******************************************************************************
//                main code
//******************************************************************************
assign overdrive_out = overdrive;

always @(posedge clk or negedge reset)begin
	if(!reset)begin
		overdrive = 16'b0;
	end
	else if(clk_enable) begin
		if(overdrive_in > 0 && overdrive_in > threshold)	
			overdrive <= threshold;
		else if(overdrive_in < 0 && overdrive_in < - threshold)
			overdrive <= -threshold;
		else
			overdrive <= overdrive_in;
	end
	else
		overdrive <= overdrive;
end

  
endmodule
  